language: node_js
node_js:
  - 14

services:
  - docker  

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
#Build
  - docker --version #print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
#Tagging
  - docker tag udagram-api-feed sphesihlemtwa/udagram-api-feed:v2
  - docker tag udagram-api-user sphesihlemtwa/udagram-api-user:v2
  - docker tag udagram-frontend sphesihlemtwa/udagram-frontend:v2
  - docker tag reverseproxy sphesihlemtwa/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sphesihlemtwa/udagram-api-feed:v2
  - docker push sphesihlemtwa/udagram-api-user:v2
  - docker push sphesihlemtwa/udagram-frontend:v2
  - docker push sphesihlemtwa/reverseproxy:v2